kind: Deployment
apiVersion: apps/v1
metadata: 
  name: valheim
  labels: 
    app: valheim
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: valheim
  template:
    metadata: 
      labels:
        app: valheim
    spec:
      containers:
        - name: valheim
          image: gcr.io/myfactorioserver/valheim
          env:
            - name: TZ
              value: "Asia/Tokyo"
            - name: cap_add
              value: sys_nice          
            - name: SERVER_PASS
              value: "speee"
            - name: SERVER_PUBLIC
              value: "false"
            - name: BEPINEX
              value: "true"
          volumeMounts:
            - name: valheim-data
              mountPath: /opt/valheim
              subPath: valheim
            - name: valheim-data
              mountPath: /config
              subPath: valheim-config
          ports:
            - containerPort: 2456
              protocol: UDP
            - containerPort: 2457
              protocol: UDP
            - containerPort: 2458
              protocol: UDP
            - containerPort: 9001
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: valheim-data
          persistentVolumeClaim: 
            claimName: pvc-name
