kind: Deployment
apiVersion: apps/v1
metadata: 
  name: minecraft
  labels: 
    app: minecraft
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: minecraft
  template:
    metadata: 
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server
          env:
            - name: EULA
              value: "true"
            - name: TZ
              value: Asia/Tokyo
            - name: DIFFICULTY
              value: "hard"
            - name: VERSION
              value: "1.12.2"
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
          ports:
            - name: tcp
              containerPort: 25565
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 30
          livenessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 30
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: minecraft-data
          persistentVolumeClaim: 
            claimName: pvc-name
