kind: Deployment
apiVersion: apps/v1
metadata: 
  name: minecraft
  labels: 
    app: minecraft
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: minecraft
  template:
    metadata: 
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:latest
          env:
            - name: EULA
              value: "true"
            - name: TZ
              value: Asia/Tokyo
            - name: VERSION
              value: 1.16.5
          volumeMounts:
            - name: minecraftData
              mountPath: /data
          ports:
            - name: tcp
              containerPort: 25565
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 30
          livenessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 30
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 1.2
              memory: 13Gi
            limits:
              cpu: 1.93
              memory: 13.94Gi            
      volumes:
        - name: minecraftData
          persistentVolumeClaim: 
            claimName: pvc-name
