kind: Deployment
apiVersion: apps/v1
metadata: 
  name: minecraft
  labels: 
    app: minecraft
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: minecraft
  template:
    metadata: 
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:latest
          env:
            - name: EULA
              value: "true"
            - name: TZ
              value: Asia/Tokyo
            - name: VERSION
              value: "1.16.5"
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
          ports:
            - name: tcp
              containerPort: 25565
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 1
              memory: 12Gi
            limits:
              cpu: 1
              memory: 13.94Gi            
      volumes:
        - name: minecraft-data
          persistentVolumeClaim: 
            claimName: pvc-name
